=== joelccarvalho/DAW2020/T2/projRecord.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT project_record (identification, work_team, abstract, deliverables) >

<!ATTLIST project_record pr_name CDATA #REQUIRED>

<!ELEMENT identification (key_name, title, subtitle?, begin_date, end_date, supervisors)>
<!ELEMENT key_name (style)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT begin_date (#PCDATA)>
<!ELEMENT end_date (#PCDATA)>
<!ELEMENT supervisors (supervisor)+>

<!ELEMENT supervisor (name, email)>

<!ELEMENT work_team (element)+ >
<!ELEMENT element (name, email, site?) >
<!ATTLIST element id ID #REQUIRED>

<!ELEMENT abstract (paragraph)+ >
<!ELEMENT paragraph (#PCDATA|style)* >

<!ELEMENT style (#PCDATA)>
<!ATTLIST style type (none|uppercase|bold|italic|underline) "none">

<!ELEMENT deliverables (deliverable)+ >
<!ELEMENT deliverable (name, link)>
<!ATTLIST deliverable id ID #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT link (#PCDATA)>

=== joelccarvalho/DAW2020/T2/projRecord.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project_record SYSTEM "projRecord.dtd">
<?xml-stylesheet href="projRecord.css"?>

<project_record pr_name="Project Record"> 
  <identification>
    <key_name>
      <style type="uppercase">
        T2_MEI_PG42837
      </style>
    </key_name>
    <title>TPC 2</title>
    <subtitle>Project Record TPC 2</subtitle>
    <begin_date>Outubro 2020</begin_date>
    <end_date>Outubro 2020</end_date>
    <supervisors>
      <supervisor>
        <name>José Carlos Ramalho</name>
        <email>jcr@di.uminho.pt</email>
      </supervisor>
    </supervisors>
  </identification>
  <work_team>
    <element id="el1">
      <name>Joel Costa Carvalho</name>
      <email>pg42837@alunos.uminho.pt</email>
    </element>
  </work_team>
  <abstract>
    <paragraph>
      O projeto desenvolvido consiste na construção de um <style type="italic">project record</style> 
      em <style type="uppercase">XML </style> e consequentemente o seu 
      <style type="uppercase">DTD</style> 
      devidamente estruturado, de modo a efetuar uma avaliação precisa da informação
      digitada no <style type="uppercase">XML </style>.
    </paragraph>
    <paragraph>
      <style type="uppercase">XML </style>
      <style type="italic"> (Extensible Markup Language)</style>
      é uma recomendação da <style type="uppercase"> W3C </style>
      para gerar <style type="bold"> linguagens de marcação </style>
      para necessidades especiais. 
    </paragraph>
    <paragraph>
      <style type="uppercase">DTD </style> <style type="italic"> (Document Type Definition)</style> consiste numa definição do tipo de documento.
      Ou seja, define a estrutura e quais os elementos e atributos pertencentes a um determinado <style type="uppercase">XML </style>.
      Com isto, obtemos uma análise e validação de cada elemento do ficheiro <style type="uppercase">XML </style>.
    </paragraph>
    <paragraph>
      Futuramente, iremos introduzir o <style type="uppercase">XSLT </style>
      <style type="italic">(eXtensible Stylesheet Language) </style> que define apresentação dos documentos
      <style type="uppercase">XML </style> em browsers, alinhando e formatando cada elemento no formato desejado pelo programador.
    </paragraph>
  </abstract>
  <deliverables>
    <deliverable id="d1">
      <name>HTML e CSS: Gatos</name>
      <link>https://github.com/joelccarvalho/DAW2020/tree/master/T1</link>
    </deliverable>
    <deliverable id="d2">
      <name>Project Record: DTD e XML</name>
      <link>https://github.com/joelccarvalho/DAW2020/tree/master/T2</link>
    </deliverable>
  </deliverables>
</project_record>
